default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_development
  username: postgres
  password: postgres
  port: 5433
test:
  adapter: postgresql
  encoding: unicode
  database: store_api_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5433

production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
